---
title: "Installation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette details the infrastructure requirements of cs9.

We strongly recommend that you use cs9 within a Docker environment.

## Databases

Currently cs9 only works with MSSQL databases.

## Environmental variables

The following environmental variables must be available from within R. R only loads a limited amount of environmental variables by default, so you should make sure that these environmental variables are located in your `Renviron` file.

| Variable                        | Value                           | Description                                                           |
|------------------|------------------|------------------------------------|
| CS9_AUTO                        | 0                               | Is this auto or interactive                                           |
| CS9_PATH                        | '/input'                        | The base path that will be inserted when using the cs9::path function |
|                                 |                                 |                                                                       |
| CS9_DBCONFIG_ACCESS             | 'config/anon'                   |                                                                       |
| CS9_DBCONFIG_DRIVER             | 'ODBC Driver 17 for SQL Server' |                                                                       |
| CS9_DBCONFIG_PORT               | 1433                            |                                                                       |
| CS9_DBCONFIG_USER               | 'SA'                            |                                                                       |
| CS9_DBCONFIG_PASSWORD           | 'yourStrongPassword100'         |                                                                       |
| CS9_DBCONFIG_TRUSTED_CONNECTION | 'no'                            |                                                                       |
| CS9_DBCONFIG_SSLMODE | 'no'                            |                                                                       |
| CS9_DBCONFIG_SERVER             | 'dm-prod'                       |                                                                       |
|                                 |                                 |                                                                       |
| CS9_DBCONFIG_SCHEMA_CONFIG      | 'dbo'                           |                                                                       |
| CS9_DBCONFIG_DB_CONFIG          | 'sc_interactive_config'         |                                                                       |
|                                 |                                 |                                                                       |
| CS9_DBCONFIG_SCHEMA_ANON        | 'dbo'                           |                                                                       |
| CS9_DBCONFIG_DB_ANON            | 'sc_interactive_anon'           |                                                                       |
|                                 |                                 |                                                                       |
|                                 |                                 |                                                                       |

## Docker

An example docker-compose file is available [here](https://github.com/csids/docker-examples-csids/blob/main/csids-cs9-single-user-docker-compose/docker-compose.yml).


